In [5]:
pip install quandl --no-warn-script-location

Requirement already satisfied: quandl in c:\users\unike\desktop\winter_internship\flight_delay_prediction\env\lib\site-packages (3.6.0)
Requirement already satisfied: inflection>=0.3.1 in c:\users\unike\desktop\winter_internship\flight_delay_prediction\env\lib\site-packages (from quandl) (0.5.1)
Requirement already satisfied: six in c:\users\unike\desktop\winter_internship\flight_delay_prediction\env\lib\site-packages (from quandl) (1.15.0)
Requirement already satisfied: pandas>=0.14 in c:\users\unike\desktop\winter_internship\flight_delay_prediction\env\lib\site-packages (from quandl) (1.2.1)
Requirement already satisfied: requests>=2.7.0 in c:\users\unike\desktop\winter_internship\flight_delay_prediction\env\lib\site-packages (from quandl) (2.25.1)
Requirement already satisfied: more-itertools in c:\users\unike\desktop\winter_internship\flight_delay_prediction\env\lib\site-packages (from quandl) (8.6.0)
Requirement already satisfied: numpy>=1.8 in c:\users\unike\desktop\winter_internship\flight_delay_prediction\env\lib\site-packages (from quandl) (1.19.2)
Requirement already satisfied: python-dateutil in c:\users\unike\desktop\winter_internship\flight_delay_prediction\env\lib\site-packages (from quandl) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\unike\desktop\winter_internship\flight_delay_prediction\env\lib\site-packages (from pandas>=0.14->quandl) (2020.5)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\unike\desktop\winter_internship\flight_delay_prediction\env\lib\site-packages (from requests>=2.7.0->quandl) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\unike\desktop\winter_internship\flight_delay_prediction\env\lib\site-packages (from requests>=2.7.0->quandl) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\unike\desktop\winter_internship\flight_delay_prediction\env\lib\site-packages (from requests>=2.7.0->quandl) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\unike\desktop\winter_internship\flight_delay_prediction\env\lib\site-packages (from requests>=2.7.0->quandl) (1.26.3)
Note: you may need to restart the kernel to use updated packages.

In [86]:
import quandl

In [87]:
quandl.ApiConfig.api_key = "iTpxtDeRE8aWAzzsm-PV"

In [88]:
df = quandl.get("EOD/AAPL", authtoken="iTpxtDeRE8aWAzzsm-PV")
df

,Open,High,Low,Close,Volume,Dividend,Split,Adj_Open,Adj_High,Adj_Low,Adj_Close,Adj_Volume
Date,,,,,,,,,,,,
2013-09-03,493.10,500.600,487.350,488.580,11854600.0,0.0,1.0,15.619650,15.857223,15.437510,15.476472,331928800.0
2013-09-04,499.56,502.240,496.280,498.691,12322600.0,0.0,1.0,15.824280,15.909173,15.720381,15.796753,345032800.0
2013-09-05,500.25,500.680,493.640,495.270,8441700.0,0.0,1.0,15.846136,15.859757,15.636755,15.688388,236367600.0
2013-09-06,498.44,499.380,489.950,498.220,12840200.0,0.0,1.0,15.788802,15.818578,15.519869,15.781833,359525600.0
2013-09-09,505.00,507.920,503.480,506.170,12167400.0,0.0,1.0,15.996600,16.089095,15.948451,16.033661,340687200.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2017-12-21,174.17,176.020,174.100,175.010,20949896.0,0.0,1.0,41.899570,42.344619,41.882730,42.101646,83799584.0
2017-12-22,174.68,175.424,174.500,175.010,16349444.0,0.0,1.0,42.022259,42.201241,41.978957,42.101646,65397776.0
2017-12-26,170.80,171.470,169.679,170.570,33185536.0,0.0,1.0,41.088858,41.250038,40.819183,41.033528,132742144.0
2017-12-27,170.10,170.780,169.710,170.600,21498213.0,0.0,1.0,40.920461,41.084047,40.826640,41.040745,85992852.0
2017-12-28,171.00,171.850,170.480,171.080,16480187.0,0.0,1.0,41.136972,41.341454,41.011877,41.156217,65920748.0

In [89]:
df.isna().sum()

Open          0
High          0
Low           0
Close         0
Volume        0
Dividend      0
Split         0
Adj_Open      0
Adj_High      0
Adj_Low       0
Adj_Close     0
Adj_Volume    0
dtype: int64

In [90]:
df['Split'].value_counts()

1.0    1089
7.0       1
Name: Split, dtype: int64

In [91]:
#High low percentage column
df['HL_PCT']=(df['Adj_High']-df['Adj_Low'])/df['Adj_Close']*100.0

In [92]:
df

,Open,High,Low,Close,Volume,Dividend,Split,Adj_Open,Adj_High,Adj_Low,Adj_Close,Adj_Volume,HL_PCT
Date,,,,,,,,,,,,,
2013-09-03,493.10,500.600,487.350,488.580,11854600.0,0.0,1.0,15.619650,15.857223,15.437510,15.476472,331928800.0,2.711941
2013-09-04,499.56,502.240,496.280,498.691,12322600.0,0.0,1.0,15.824280,15.909173,15.720381,15.796753,345032800.0,1.195129
2013-09-05,500.25,500.680,493.640,495.270,8441700.0,0.0,1.0,15.846136,15.859757,15.636755,15.688388,236367600.0,1.421447
2013-09-06,498.44,499.380,489.950,498.220,12840200.0,0.0,1.0,15.788802,15.818578,15.519869,15.781833,359525600.0,1.892738
2013-09-09,505.00,507.920,503.480,506.170,12167400.0,0.0,1.0,15.996600,16.089095,15.948451,16.033661,340687200.0,0.877176
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-12-21,174.17,176.020,174.100,175.010,20949896.0,0.0,1.0,41.899570,42.344619,41.882730,42.101646,83799584.0,1.097080
2017-12-22,174.68,175.424,174.500,175.010,16349444.0,0.0,1.0,42.022259,42.201241,41.978957,42.101646,65397776.0,0.527970
2017-12-26,170.80,171.470,169.679,170.570,33185536.0,0.0,1.0,41.088858,41.250038,40.819183,41.033528,132742144.0,1.050009
2017-12-27,170.10,170.780,169.710,170.600,21498213.0,0.0,1.0,40.920461,41.084047,40.826640,41.040745,85992852.0,0.627198
2017-12-28,171.00,171.850,170.480,171.080,16480187.0,0.0,1.0,41.136972,41.341454,41.011877,41.156217,65920748.0,0.800795

In [93]:
#percentage Change Column
df['PCT_change']=(df['Adj_Close']-df['Adj_Open'])/df['Adj_Open']*100.0
df

,Open,High,Low,Close,Volume,Dividend,Split,Adj_Open,Adj_High,Adj_Low,Adj_Close,Adj_Volume,HL_PCT,PCT_change
Date,,,,,,,,,,,,,,
2013-09-03,493.10,500.600,487.350,488.580,11854600.0,0.0,1.0,15.619650,15.857223,15.437510,15.476472,331928800.0,2.711941,-0.916650
2013-09-04,499.56,502.240,496.280,498.691,12322600.0,0.0,1.0,15.824280,15.909173,15.720381,15.796753,345032800.0,1.195129,-0.173953
2013-09-05,500.25,500.680,493.640,495.270,8441700.0,0.0,1.0,15.846136,15.859757,15.636755,15.688388,236367600.0,1.421447,-0.995502
2013-09-06,498.44,499.380,489.950,498.220,12840200.0,0.0,1.0,15.788802,15.818578,15.519869,15.781833,359525600.0,1.892738,-0.044138
2013-09-09,505.00,507.920,503.480,506.170,12167400.0,0.0,1.0,15.996600,16.089095,15.948451,16.033661,340687200.0,0.877176,0.231683
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-12-21,174.17,176.020,174.100,175.010,20949896.0,0.0,1.0,41.899570,42.344619,41.882730,42.101646,83799584.0,1.097080,0.482287
2017-12-22,174.68,175.424,174.500,175.010,16349444.0,0.0,1.0,42.022259,42.201241,41.978957,42.101646,65397776.0,0.527970,0.188917
2017-12-26,170.80,171.470,169.679,170.570,33185536.0,0.0,1.0,41.088858,41.250038,40.819183,41.033528,132742144.0,1.050009,-0.134660
2017-12-27,170.10,170.780,169.710,170.600,21498213.0,0.0,1.0,40.920461,41.084047,40.826640,41.040745,85992852.0,0.627198,0.293945
2017-12-28,171.00,171.850,170.480,171.080,16480187.0,0.0,1.0,41.136972,41.341454,41.011877,41.156217,65920748.0,0.800795,0.046784

In [94]:
df.drop(['Open','High','Low','Close','Volume','Dividend','Split','Adj_Open','Adj_High','Adj_Low'],axis=1,inplace=True)

In [95]:
df

            Adj_Close   Adj_Volume    HL_PCT  PCT_change
Date
2013-09-03  15.476472  331928800.0  2.711941   -0.916650
2013-09-04  15.796753  345032800.0  1.195129   -0.173953
2013-09-05  15.688388  236367600.0  1.421447   -0.995502
2013-09-06  15.781833  359525600.0  1.892738   -0.044138
2013-09-09  16.033661  340687200.0  0.877176    0.231683
...               ...          ...       ...         ...
2017-12-21  42.101646   83799584.0  1.097080    0.482287
2017-12-22  42.101646   65397776.0  0.527970    0.188917
2017-12-26  41.033528  132742144.0  1.050009   -0.134660
2017-12-27  41.040745   85992852.0  0.627198    0.293945
2017-12-28  41.156217   65920748.0  0.800795    0.046784

[1090 rows x 4 columns]

In [96]:
df.isna().sum()

Adj_Close     0
Adj_Volume    0
HL_PCT        0
PCT_change    0
dtype: int64

In [97]:
import math

In [98]:
col = 'Adj_Close'
out = math.ceil(0.01* len(df)) #taking 1 day out
out

11

In [99]:
df.fillna(-99999, inplace = True)
df['label']= df[col].shift(-out)

In [100]:
df

            Adj_Close   Adj_Volume    HL_PCT  PCT_change      label
Date
2013-09-03  15.476472  331928800.0  2.711941   -0.916650  14.719406
2013-09-04  15.796753  345032800.0  1.195129   -0.173953  14.960780
2013-09-05  15.688388  236367600.0  1.421447   -0.995502  14.805882
2013-09-06  15.781833  359525600.0  1.892738   -0.044138  15.541726
2013-09-09  16.033661  340687200.0  0.877176    0.231683  15.492944
...               ...          ...       ...         ...        ...
2017-12-21  42.101646   83799584.0  1.097080    0.482287        NaN
2017-12-22  42.101646   65397776.0  0.527970    0.188917        NaN
2017-12-26  41.033528  132742144.0  1.050009   -0.134660        NaN
2017-12-27  41.040745   85992852.0  0.627198    0.293945        NaN
2017-12-28  41.156217   65920748.0  0.800795    0.046784        NaN

[1090 rows x 5 columns]

In [101]:
df['label'].isna().sum()

11

In [102]:
df=df.dropna()

In [103]:
df

            Adj_Close   Adj_Volume    HL_PCT  PCT_change      label
Date
2013-09-03  15.476472  331928800.0  2.711941   -0.916650  14.719406
2013-09-04  15.796753  345032800.0  1.195129   -0.173953  14.960780
2013-09-05  15.688388  236367600.0  1.421447   -0.995502  14.805882
2013-09-06  15.781833  359525600.0  1.892738   -0.044138  15.541726
2013-09-09  16.033661  340687200.0  0.877176    0.231683  15.492944
...               ...          ...       ...         ...        ...
2017-12-06  40.658243  114240000.0  2.215668    0.901493  42.101646
2017-12-07  40.732819  102693232.0  0.903614    0.171567  42.101646
2017-12-08  40.744848   93420924.0  1.287123   -0.656930  41.033528
2017-12-11  41.538719  141095036.0  2.374472    2.050827  41.040745
2017-12-12  41.305369   77636920.0  0.541060   -0.261400  41.156217

[1079 rows x 5 columns]

In [105]:
import numpy as np
from sklearn.model_selection import train_test_split

In [121]:
x=np.array(df.drop(['label'],1))

In [122]:
x

array([[ 1.54764725e+01,  3.31928800e+08,  2.71194073e+00,
        -9.16649767e-01],
       [ 1.57967529e+01,  3.45032800e+08,  1.19512885e+00,
        -1.73953079e-01],
       [ 1.56883878e+01,  2.36367600e+08,  1.42144689e+00,
        -9.95502249e-01],
       ...,
       [ 4.07448475e+01,  9.34209240e+07,  1.28712287e+00,
        -6.56930025e-01],
       [ 4.15387189e+01,  1.41095036e+08,  2.37447154e+00,
         2.05082742e+00],
       [ 4.13053688e+01,  7.76369200e+07,  5.41059988e-01,
        -2.61399942e-01]])

In [123]:
y=np.array(df['label'])
y

array([14.71940567, 14.96078011, 14.80588234, ..., 41.03352802,
       41.04074503, 41.15621723])

In [124]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [125]:
from sklearn.preprocessing import MinMaxScaler

In [126]:
feature_scale= MinMaxScaler().fit(x_train)

In [127]:
x_train_scaled= feature_scale.transform(x_train)

In [128]:
x_test_scaled= feature_scale.transform(x_test)

In [132]:
print("shape of original dataset :", df.shape)
print("shape of input - training set", x_train.shape)
print("shape of output - training set", y_train.shape)
print("shape of input - testing set", x_test.shape)
print("shape of output - testing set", y_test.shape)

shape of original dataset : (1079, 5)
shape of input - training set (863, 4)
shape of output - training set (863,)
shape of input - testing set (216, 4)
shape of output - testing set (216,)

In [130]:
from sklearn.linear_model import LinearRegression

In [131]:
predictor = LinearRegression(n_jobs=-1) 
predictor.fit(x_train, y_train)

LinearRegression(n_jobs=-1)

In [133]:
outcome = predictor.predict(x_test)

In [135]:
coefficients = predictor.coef_

In [140]:
print("Outcome:",outcome)
print("Coefficients:",coefficients)

Outcome: [27.20933018 25.9097667  23.23647308 25.93377661 21.51604196 35.07334782
 41.4296979  22.50200759 26.98766159 28.46275633 26.38164848 23.40850919
 25.13135615 35.02761481 25.01885823 25.59501933 25.07155477 27.16821507
 29.19518716 26.0733301  26.34766115 40.7550254  23.25538705 27.1442318
 16.23501569 15.87011114 30.50761235 26.67173122 26.61774263 34.62864185
 21.79300447 37.70755466 22.22875533 22.89906476 32.82262549 25.37077549
 17.1836108  15.48337772 37.86018091 28.83530586 29.26136156 29.83952975
 17.65103296 26.3897794  20.78254195 29.06079469 22.75833344 22.85272032
 25.27204936 22.10866373 24.29380619 30.36698911 29.34803157 23.35800244
 29.10513332 22.47839578 15.69624627 16.08428955 29.80583614 30.08826174
 21.36735253 24.78413977 28.74995038 30.48824005 26.71635234 38.48724723
 23.3976399  29.18501351 29.22393397 37.40709751 38.9912051  30.41244235
 17.60122068 38.85204772 15.90784593 25.91623816 20.96095683 29.15425815
 25.13007757 27.77304969 38.23186292 28.02755105 41.98280847 15.80174346
 22.10887944 38.4687405  41.03359155 36.73383442 29.7893473  29.95248056
 22.94078817 19.53251538 34.07731826 26.36678367 25.16813568 22.64913416
 25.82160103 29.11420946 16.98514276 27.47861752 26.32136141 33.34558707
 22.37491868 27.21830323 28.60613729 17.79819104 16.769179   35.00419325
 25.08271377 26.91341142 34.28850848 16.95162858 17.53398251 26.82363126
 23.45884027 28.21356979 37.07967261 28.17359225 26.17439026 28.13645937
 27.37196263 21.96486378 27.05503481 26.34658087 25.05955777 17.61948865
 27.84269187 30.10513229 17.64027113 24.18372601 20.3351828  22.16558289
 26.85850678 23.16089006 22.10552131 29.28370844 26.63916718 40.88795068
 37.82955776 20.87948327 22.47002671 26.39699551 21.13662691 26.16212344
 15.67351145 29.37638868 22.81487251 16.11173948 22.27780209 18.02852147
 26.70675936 38.37970028 32.29715886 25.2813458  23.32309689 22.98081735
 27.34690396 23.21814358 22.25757907 23.69828757 28.49037443 38.82827804
 27.13012629 26.76305682 27.68017351 25.90084456 39.4271009  38.05029675
 26.43674406 25.15045059 26.88950236 36.49138183 25.68483466 33.46094672
 26.22143688 22.54062792 18.22435862 38.35264018 28.03971119 25.46326361
 34.62530318 24.97013807 29.15699933 22.49523764 22.44362869 27.17187744
 27.97765066 39.11659904 20.77192388 32.84186501 31.71791372 23.13162884
 17.17242512 40.58406538 33.3048834  38.32241701 32.732773   41.3565192
 25.28404486 36.13574589 40.91784264 34.40111457 28.30847562 27.00098118
 28.00446499 27.62041452 26.10829305 29.56807411 25.89623485 15.10489061
 35.05238194 33.96920422 15.74744052 33.73574767 29.55084019 27.99134972]
Coefficients: [ 9.83714824e-01 -9.79090252e-10  1.84969304e-02 -2.85692543e-02]

In [141]:
from sklearn.metrics import mean_squared_error

In [142]:
y_pred=outcome
tt=mean_squared_error(y_test,y_pred)

In [143]:
tt

1.5674780454025363